### ISSUE TITLE
Implement service registry and discovery that support consul and zookeeper

### ISSUE THREAD

**Issue by s101d1** [networknt/light-java#10]
Is there service discovery feature just like in [spring boot](https://spring.io/guides/gs/service-registration-and-discovery/)?

**Comment by stevehu** [comment]
Service registration and discovery are half way through already and the current plan is to support consul and zookeeper. The discovery will be client side discovery in our client module with load balancing in the same module. This design eliminate the proxy so that client and service are communicated directly. Initially, we are planning to support round robin and local first load balancer but more can be added later on. Thanks for your question.

**Comment by stevehu** [comment]
The basic implementation is almost done and the following needs to be considered.

1. Need to update server module to register itself during startup and switch it on once server is up.
2. Need to update client module to integrate with discovery module and load balancer as well.
3. Need to make sure it works with services deployed in docker containers.
