### ISSUE TITLE
Implement GraphQL support with light-java-graphql

### ISSUE THREAD

**Issue by emrul** [networknt/light-java#8]
I read that GraphQL is a mid-term goal on the road map.  I am interested in this.

From the docs I see that it seems to strongly encourage starting a project from a Swagger spec so I'm interested to understand how GraphQL support might be incorporated into this project (just at a high level)?

**Comment by stevehu** [comment]
The current focus is to get RESTful support and light-oauth2 production ready as one of our major clients is planning to have an application on production early next year. Regarding to websocket, rpc and graphql, there will be separate handlers implemented and injected in the handler chain before RESTful handlers so that these can bypass all swagger related handlers. One example can be found at https://github.com/networknt/light-java-example/tree/master/webserver
that demos how to serve files along with RESTful APIs at the same time. Let me know if you need more details.

**Comment by emrul** [comment]
Thanks, that's really useful info!

**Comment by stevehu** [comment]
Until now, I am always thinking to implement websocket, rpc and graphql in the same code based but it look like they are not compatible at all. At this moment, I am seriously thinking to split the current light-java to spin off light-java-rest and then in the future to implement light-java-rpc with websocket support and light-java-graphql. All of them are based on some common libraries within light-java. Nothing has been done yet and I want to hear from you guys.

**Comment by emrul** [comment]
I think separating them as you propose makes most sense.  GraphQL in particular is very different from plain REST and I can't imagine a 'clean' way to incorporate all the nuances into a uniform codebase.

**Comment by stevehu** [comment]
Yes. That is exactly what we do. The routing, security etc would be totally different. It is just I don't have time to work on it yet. Everything is driven by demand at the moment and we don't have enough resources. Things might change in the future.

**Comment by stevehu** [comment]
I have checked in a working in progress version of [light-java-graphql](https://github.com/networknt/light-java-graphql) and an [example](https://github.com/networknt/light-java-example/tree/master/graphql/hello). To compile light-java-graphql and hello example, you need the latest version of light-java from master. I will release both once they are fully tested. Thanks.
